apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-basic-app-3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://lusoal.github.io/helm-charts-examples/'
    chart: 'python-application-chart'
    targetRevision: '0.1.0'
    helm:
      values: |
        name: python-basic-app-3
        namespace: python-basic-app-3
        replicaCount: 1
        image:
          repository: 054678736585.dkr.ecr.us-west-2.amazonaws.com/python-basic-app
          tag: "dev-hjdgs"
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          port: 80
        env:
          S3_BUCKET_NAME: 'python-application-3-kjsahjdk'
        serviceAccount:
          create: true
          name: python-basic-app-3
          iamRoleArn: 'arn:aws:iam::054678736585:role/python-application-3-role'
  destination:
    name: "in-cluster"
    namespace: python-basic-app-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true