---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: provision-iac-bucket-irsa
  namespace: argo-workflows
spec:
  entrypoint: main
  serviceAccountName: argo-workflow
  arguments:
    parameters:
      - name: REPO_URL
        value: "https://github.com/lusoal/terraform-examples"
      - name: GIT_BRANCH
        value: "main"
      - name: ARTIFACT_BUCKET
        value: "getting-started20240610210044198100000001"
      - name: APPLICATION_NAME
      - name: ROLE_NAME
      - name: BUCKET_NAME
  templates:
    - name: main
      steps:
        - - name: clone-repository
            template: clone-repository
            arguments:
              parameters:
                - name: REPO_URL
                  value: "{{workflow.parameters.REPO_URL}}"
                - name: GIT_BRANCH
                  value: "{{workflow.parameters.GIT_BRANCH}}"
        - - name: create-infrastructure
            template: create-infrastructure
            arguments:
              parameters:
                - name: APPLICATION_NAME
                  value: "{{workflow.parameters.APPLICATION_NAME}}"
                - name: ROLE_NAME
                  value: "{{workflow.parameters.ROLE_NAME}}"
                - name: BUCKET_NAME
                  value: "{{workflow.parameters.BUCKET_NAME}}"
                - name: ARTIFACT_BUCKET
                  value: "{{workflow.parameters.ARTIFACT_BUCKET}}"
    - name: clone-repository
      inputs:
        parameters:
          - name: REPO_URL
          - name: GIT_BRANCH
      container:
        image: "054678736585.dkr.ecr.us-west-2.amazonaws.com/argo-workflows-internal:3"
        command: ["/bin/sh", "-c"]
        args: ["./01-clone-repository.sh '{{inputs.parameters.REPO_URL}}' '{{inputs.parameters.GIT_BRANCH}}'"]
        volumeMounts:
        - name: workdir
          mountPath: /mnt/vol 
    - name: create-infrastructure
      inputs:
        parameters:
          - name: APPLICATION_NAME
          - name: ROLE_NAME
          - name: BUCKET_NAME
          - name: ARTIFACT_BUCKET
      container:
        image: "054678736585.dkr.ecr.us-west-2.amazonaws.com/argo-workflows-internal:3"
        command: ["/bin/sh", "-c"]
        args: ["./02-apply-terraform.sh '{{inputs.parameters.APPLICATION_NAME}}' '{{inputs.parameters.ROLE_NAME}}' '{{inputs.parameters.BUCKET_NAME}}' '{{inputs.parameters.ARTIFACT_BUCKET}}'"]
        volumeMounts:
        - name: workdir
          mountPath: /mnt/vol
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
